plugins{id 'fabric-loom' version "${loom_version}";id 'maven-publish'}
version=project.mod_version
group=project.maven_group
base{archivesName=project.archives_base_name}
repositories{mavenCentral()}
dependencies{minecraft "com.mojang:minecraft:${project.minecraft_version}";mappings loom.officialMojangMappings();modImplementation "net.fabricmc:fabric-loader:${project.loader_version}";modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"}
processResources{inputs.property "version",project.version;filesMatching("fabric.mod.json"){expand "version":project.version}}
tasks.withType(JavaCompile).configureEach{options.release=21}
java{withSourcesJar();sourceCompatibility=JavaVersion.VERSION_21;targetCompatibility=JavaVersion.VERSION_21}
tasks.register('apiJar',Jar){archiveClassifier='api';from sourceSets.main.output;include 'com/alex/universalcrowbarapi/api/**';include 'com/alex/universalwrenchapi/api/**';include 'com/alex/universaltoolsapi/screwdriver/api/**';include 'com/alex/universaltoolsapi/screwdriver/item/**';include 'com/alex/universalshearsapi/api/**';include 'com/alex/universalshearsapi/item/**';include 'com/alex/universalshieldapi/api/**';include 'com/alex/universalshieldapi/item/**';include 'com/alex/universalrangedweaponapi/api/**';include 'com/alex/universalrangedweaponapi/item/**';include 'com/alex/datadrivenpotionsapi/api/**';include 'com/alex/datadrivenitemattributesapi/api/**';include 'com/alex/firguiapi/api/**'}
tasks.named('build'){dependsOn tasks.named('apiJar')}
