package com.alex.datadrivenitemattributesapi;
import com.alex.datadrivenitemattributesapi.api.*;import com.google.gson.*;import com.google.gson.reflect.TypeToken;import com.mojang.brigadier.arguments.*;
import net.fabricmc.api.ModInitializer;import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.commands.Commands;import net.minecraft.network.chat.Component;import net.minecraft.world.item.ItemStack;
import java.io.*;import java.lang.reflect.Type;import java.nio.file.*;import java.util.*;
public final class DataDrivenItemAttributesApiMod implements ModInitializer{
 public static final String MOD_ID="data-driven-item-attributes-api";private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();private static Path dir,file;
 public void onInitialize(){examples();dir=FabricLoader.getInstance().getConfigDir().resolve("universal-tool-apis/item_attributes");file=dir.resolve("overrides.json");loadDefs();loadValues();DataDrivenItemAttributesApi.addListener((i,d,o,n)->save());commands();}
 private static void examples(){DataDrivenItemAttributesApi.registerAttribute(new ItemAttributeDefinition("weight",1,0,1000,"Generic item mass/weight scalar"));DataDrivenItemAttributesApi.registerAttribute(new ItemAttributeDefinition("reach",0,-16,64,"Extra interaction reach in blocks"));DataDrivenItemAttributesApi.registerAttribute(new ItemAttributeDefinition("mining_speed",1,0,100,"Mining-speed multiplier"));DataDrivenItemAttributesApi.registerAttribute(new ItemAttributeDefinition("knockback_resistance",0,0,1,"Knockback resistance contribution"));DataDrivenItemAttributesApi.registerAttribute(new ItemAttributeDefinition("use_speed",1,.05,20,"Use/action speed multiplier"));}
 private static void loadDefs(){try{Files.createDirectories(dir);try(var s=Files.list(dir)){s.filter(p->p.getFileName().toString().endsWith(".json")&&!p.equals(file)).forEach(DataDrivenItemAttributesApiMod::def);}}catch(Exception ignored){}}
 private static void def(Path p){try(Reader r=Files.newBufferedReader(p)){JsonObject j=GSON.fromJson(r,JsonObject.class);DataDrivenItemAttributesApi.registerAttribute(new ItemAttributeDefinition(j.get("id").getAsString(),j.has("default")?j.get("default").getAsDouble():0,j.has("min")?j.get("min").getAsDouble():-Double.MAX_VALUE,j.has("max")?j.get("max").getAsDouble():Double.MAX_VALUE,j.has("description")?j.get("description").getAsString():""));}catch(Exception ignored){}}
 private static void loadValues(){if(!Files.isRegularFile(file))return;Type t=new TypeToken<Map<String,Map<String,Double>>>(){}.getType();try(Reader r=Files.newBufferedReader(file)){Map<String,Map<String,Double>> v=GSON.fromJson(r,t);if(v!=null)v.forEach((i,a)->a.forEach((k,x)->DataDrivenItemAttributesApi.loadValue(i,k,x)));}catch(Exception ignored){}}
 private static void save(){try{Files.createDirectories(dir);try(Writer w=Files.newBufferedWriter(file)){GSON.toJson(DataDrivenItemAttributesApi.valueSnapshot(),w);}}catch(Exception ignored){}}
 private static void commands(){CommandRegistrationCallback.EVENT.register((dispatcher,registryAccess,environment)->dispatcher.register(Commands.literal("itemAttribute")
  .then(Commands.literal("list").executes(c->{String x=String.join(", ",DataDrivenItemAttributesApi.definitions().keySet());c.getSource().sendSuccess(()->Component.literal("Item attributes: "+x),false);return DataDrivenItemAttributesApi.definitions().size();}))
  .then(Commands.argument("attribute",StringArgumentType.word())
   .then(Commands.literal("get").executes(c->{String id=StringArgumentType.getString(c,"attribute");ItemStack s=c.getSource().getPlayerOrException().getMainHandItem();double v=DataDrivenItemAttributesApi.get(s,id);c.getSource().sendSuccess(()->Component.literal(id+" = "+v),false);return 1;}))
   .then(Commands.literal("reset").executes(c->{String id=StringArgumentType.getString(c,"attribute");ItemStack s=c.getSource().getPlayerOrException().getMainHandItem();double v=DataDrivenItemAttributesApi.reset(s,id);c.getSource().sendSuccess(()->Component.literal(id+" reset to "+v),false);return 1;}))
   .then(Commands.literal("set").then(Commands.argument("value",DoubleArgumentType.doubleArg()).executes(c->{String id=StringArgumentType.getString(c,"attribute");double q=DoubleArgumentType.getDouble(c,"value");ItemStack s=c.getSource().getPlayerOrException().getMainHandItem();double v=DataDrivenItemAttributesApi.set(s,id,q);c.getSource().sendSuccess(()->Component.literal(id+" set to "+v),false);return 1;}))))));}
}